# Generated by Django 5.2.3 on 2025-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physiotherapistprofile',
            name='certificate',
            field=models.FileField(blank=True, help_text='Professional certificate or license document', null=True, upload_to='certificates/'),
        ),
    ]
